name: "Publish Jazzy Docs"
description: "Generate Swift/Objective-C documentation with Jazzy and publish to Github Pages"
inputs:
  config:
    description: "Path to .jazzy.yml file - preferred"
    required: false
  args:
    description: "Arguments to pass to Jazzy"
    required: false
  version:
    description: "Jazzy Version"
    required: false
  personal_access_token:
    description: "Personal access token"
    required: true
runs:
  using: "node12"
  main: "dist/main.js"
branding:
  icon: "book"
  color: "green"
